manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohansonen
#    - name: urob
#      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-with-input-processors
      import: app/west.yml
#    - name: zmk-helpers
#      remote: urob
#      revision: main
  self:
    path: config
